---
- name: This play is to download the latest jar file from nexus
  hosts: localhost
  become: true
  vars_files:
   - variables.yaml

  tasks:
     - name: download the jar file
       shell: 'curl -u admin:admin123 -L "http://192.168.1.211:8081/service/rest/v1/search/assets/download?sort=version&repository=springboot-maven-nexus-RELEASE&maven.groupId=com.cloudtechmasters&maven.artifactId=springboot-maven-course-micro-svc&maven.extension=jar" -H "accept: application/json" --output /home/ubuntu/latest.jar'
       args:
          chdir: "{{ changedir_location }}"

- name: Deploy the latest jar file to apache tomcat
  hosts: tomcat
  become: true
  vars_files:
   - variables.yaml

  tasks:
      - copy:
          src: "{{ item }}"
          dest: "{{ destination_location }}"
          owner: tomcat
          group: tomcat
          mode: u+rwx,g+rwx,o-rwx
        with_fileglob:
           - "{{ buildartifact_location }}"

...
